// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_headerMenu1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_headerMenu1));
        
        string IMigrationMetadata.Id
        {
            get { return "202412181355157_edit_headerMenu1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
